---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ghost-daemonset
  labels:
   type: cms
spec:
  selector:
   matchLabels:
    type: cms
  template:
   metadata:
    name: ghost-pod
    labels:
     type: cms
   spec: 
    containers:
     - name: ghost
       image: ghost
       env:
        - name: NODE_ENV
          value: development
       ports:
        - containerPort: 2368
          hostPort: 9090
...





