---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
  namespace: test-ns
  labels:
   type: webserver
   author: intelliqit
spec:
  replicas: 2
  selector:
   matchLabels:
     type: webserver
  template:
   metadata:
     name: httpd-pod
     labels:
      type: webserver
   spec:
    containers:
      - name: myhttpd
        image: httpd
        ports:
          - containerPort: 80
            hostPort: 8080
...




