---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  clusterIP: None
  ports:
    - port: 80
      name: web
      protocol: TCP
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  labels:
   app: nginx
spec:
  replicas: 2
  serviceName: nginx
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-v
      labels:
        app: nginx
    spec:
      containers:
       - name: nginx
         image: nginx
         ports:
           - name: web
             containerPort: 80
         volumeMounts:
          - name: my-volume
            mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
   - metadata:
      name: my-volume
     spec:
      accessModes: ["ReadWriteOnce"]
      resources:
       requests:
        storage: 200Mi
...






