---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
   type: db
spec:
 containers:
  - name: mydb
    image: intelliqit/myredis
    volumeMounts:
     - name: myvolume
       mountPath: /data/redis
 volumes:
  - name: myvolume
    emptyDir: {}
...
